### ISSUE TITLE
[FEATURE] Tracking the release

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/website#136]
### Description

We are about to release the website in coming few days and still there are some things that is still left to implement
I am taking up the task to prepare the repo for the release, however there is always scope of improvement but this issue is to track the release 

Task to be performed 

- [ ] responsiveness for `navbar`, `footer` etc
- [ ] adding links to buttons present in the website 
- [ ] testing the site on various test cases 
- [ ] uniformity in docs 
- [ ] clearing the code(removing the unused parts)

/assigned to myself 

### Additional information
Till we get this release no further PR merges should take place(still PRs are welcome)

**Comment by bishal7679** [comment]
@AvineshTripathi I wanna work with you
How may I help?
I am taking "adding links to buttons present in the website" this one
Could you provide all the links which I have to link like `learn more` button and etc.

**Comment by AvineshTripathi** [comment]
Please firstly search for buttons or text with href or anything through out the website repo and check what all are missing prepare a doc to missing links and then I'll send all those at one time(asking for individual would make things difficult ). Is that ok?

**Comment by bishal7679** [comment]
Yes It will be better.
I am preparing a doc for all the missing links from the website
Then I will inform you as soon as possible 👍

**Comment by bishal7679** [comment]
@AvineshTripathi please check out this doc
I mentioned all the missing links here
https://github.com/bishal7679/Missing_Link/blob/main/missing_links.md
